/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.0
processor: MC56F83763
package_id: MC56F83763AVLH
mcu_data: ksdk2_0
processor_version: 13.0.1
pin_labels:
- {pin_num: '13', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O, label: I_bat, identifier: TP6}
- {pin_num: '47', pin_signal: GPIOE2/PWMA_1B/XB_OUT6, label: SR_PWM2, identifier: PWM_LED2;GE2}
- {pin_num: '48', pin_signal: GPIOE3/PWMA_1A/XB_OUT7, label: SR_PWM1, identifier: PWM_LED3;GE3}
- {pin_num: '1', pin_signal: TCK/GPIOD2, label: LLC_TCK}
- {pin_num: '2', pin_signal: RESETB/GPIOD4, label: LLC_RESET}
- {pin_num: '3', pin_signal: GPIOC0/EXTAL/CLKIN0, label: Bulk_OK, identifier: Bulk_OK}
- {pin_num: '9', pin_signal: GPIOA7/ANA7, label: TEST_GPIO0, identifier: TEST_GPIO0}
- {pin_num: '10', pin_signal: GPIOA6/ANA6, label: TEST_GPIO1, identifier: TEST_GPIO1}
- {pin_num: '11', pin_signal: GPIOA5/ANA5, label: TEST_GPIO2, identifier: TEST_GPIO2}
- {pin_num: '14', pin_signal: GPIOA1/ANA1/CMPA_IN0, label: I_LLC, identifier: TP7}
- {pin_num: '15', pin_signal: GPIOA2/ANA2/VREFHA/CMPA_IN1, label: V_out_FB}
- {pin_num: '24', pin_signal: GPIOB0/ANB0/CMPB_IN3, label: V_bat_FB}
- {pin_num: '27', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3, label: OTP_S}
- {pin_num: '33', pin_signal: GPIOC8/MISO0/RXD0/XB_IN9, label: Bulk_High_Low, identifier: Bulk_High_Low}
- {pin_num: '34', pin_signal: GPIOC9/SCLK0/XB_IN4/TXD0/XB_OUT8, label: B2B_On, identifier: B2B_On}
- {pin_num: '45', pin_signal: GPIOE0/PWMA_0B/XB_OUT4, label: LLC_2}
- {pin_num: '46', pin_signal: GPIOE1/PWMA_0A/XB_OUT5, label: LLC_1}
- {pin_num: '51', pin_signal: GPIOE4/PWMA_2B/XB_IN2/XB_OUT8, label: LLC_4}
- {pin_num: '52', pin_signal: GPIOE5/PWMA_2A/XB_IN3/XB_OUT9, label: LLC_3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_sim.h"
#include "fsl_gpio.h"
#include "fsl_xbara.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '46', peripheral: PWMA, signal: 'A, 0', pin_signal: GPIOE1/PWMA_0A/XB_OUT5}
  - {pin_num: '5', peripheral: QSCI0, signal: TXD, pin_signal: GPIOC2/TXD0/TB0/XB_IN2/CLKO0}
  - {pin_num: '45', peripheral: PWMA, signal: 'B, 0', pin_signal: GPIOE0/PWMA_0B/XB_OUT4}
  - {peripheral: ADC, signal: 'SYNC, A', pin_signal: PIT0_SYNC_OUT}
  - {pin_num: '13', peripheral: ADC, signal: 'ANA, 0', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O, identifier: ''}
  - {pin_num: '24', peripheral: ADC, signal: 'ANB, 0', pin_signal: GPIOB0/ANB0/CMPB_IN3}
  - {pin_num: '52', peripheral: PWMA, signal: 'MUX_TRIG1, 0', pin_signal: GPIOE5/PWMA_2A/XB_IN3/XB_OUT9}
  - {pin_num: '51', peripheral: PWMA, signal: 'MUX_TRIG0, 0', pin_signal: GPIOE4/PWMA_2B/XB_IN2/XB_OUT8}
  - {pin_num: '18', peripheral: DACA, signal: OUT, pin_signal: GPIOC5/DACA_O/XB_IN7}
  - {pin_num: '25', peripheral: DACB, signal: OUT, pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O}
  - {pin_num: '24', peripheral: CMPB, signal: 'IN, 3', pin_signal: GPIOB0/ANB0/CMPB_IN3}
  - {peripheral: PWMA, signal: 'FAULT, 0', pin_signal: CMPA_OUT}
  - {peripheral: PWMA, signal: 'FAULT, 1', pin_signal: CMPB_OUT}
  - {pin_num: '14', peripheral: ADC, signal: 'ANA, 1', pin_signal: GPIOA1/ANA1/CMPA_IN0}
  - {pin_num: '15', peripheral: ADC, signal: 'ANA, 2', pin_signal: GPIOA2/ANA2/VREFHA/CMPA_IN1}
  - {pin_num: '27', peripheral: ADC, signal: 'ANB, 2', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3}
  - {pin_num: '9', peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: GPIOA7/ANA7, direction: OUTPUT}
  - {pin_num: '7', peripheral: QSCI0, signal: RXD, pin_signal: GPIOC3/TA0/CMPA_O/RXD0/CLKIN1}
  - {pin_num: '64', peripheral: JTAG, signal: TDI, pin_signal: TDI/GPIOD0}
  - {pin_num: '1', peripheral: JTAG, signal: TCK, pin_signal: TCK/GPIOD2}
  - {pin_num: '63', peripheral: JTAG, signal: TMS, pin_signal: TMS/GPIOD3}
  - {pin_num: '62', peripheral: JTAG, signal: TDO, pin_signal: TDO/GPIOD1}
  - {pin_num: '2', peripheral: SIM, signal: RESETB, pin_signal: RESETB/GPIOD4}
  - {pin_num: '3', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: GPIOC0/EXTAL/CLKIN0, direction: OUTPUT}
  - {pin_num: '10', peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: GPIOA6/ANA6, direction: OUTPUT}
  - {pin_num: '11', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: GPIOA5/ANA5, direction: OUTPUT}
  - {pin_num: '33', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: GPIOC8/MISO0/RXD0/XB_IN9, direction: INPUT}
  - {pin_num: '34', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: GPIOC9/SCLK0/XB_IN4/TXD0/XB_OUT8, direction: OUTPUT}
  - {pin_num: '41', peripheral: QSCI1, signal: TXD, pin_signal: GPIOF4/TXD1/XB_OUT8/PWMA_0X/PWMA_FAULT6}
  - {pin_num: '42', peripheral: QSCI1, signal: RXD, pin_signal: GPIOF5/RXD1/XB_OUT9/PWMA_1X/PWMA_FAULT7}
  - {pin_num: '47', peripheral: PWMA, signal: 'B, 1', pin_signal: GPIOE2/PWMA_1B/XB_OUT6}
  - {pin_num: '48', peripheral: PWMA, signal: 'A, 1', pin_signal: GPIOE3/PWMA_1A/XB_OUT7}
  - {pin_num: '55', peripheral: I2C0, signal: SDA, pin_signal: GPIOC14/SDA0/XB_OUT4/PWMA_FAULT4}
  - {pin_num: '56', peripheral: I2C0, signal: SCL, pin_signal: GPIOC15/SCL0/XB_OUT5/PWMA_FAULT5}
  - {pin_num: '14', peripheral: CMPA, signal: 'IN, 0', pin_signal: GPIOA1/ANA1/CMPA_IN0, identifier: ''}
  - {pin_num: '13', peripheral: CMPA, signal: 'IN, 3', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* GPIOA IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOA);
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOD IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOD);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* Enable peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMode(BOARD_TP6_GPIO, BOARD_TP6_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_A0_ANA0_and_CMPA_IN3);
    /* Enable peripheral functionality on pin GPIOA1 (pin 14) */
    GPIO_PinSetPeripheralMode(BOARD_TP7_GPIO, BOARD_TP7_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA2 (pin 15) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* GPIO functionality on pin GPIOA5 (pin 11) */
    GPIO_PinSetPeripheralMode(BOARD_TEST_GPIO2_GPIO, BOARD_TEST_GPIO2_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOA6 (pin 10) */
    GPIO_PinSetPeripheralMode(BOARD_TEST_GPIO1_GPIO, BOARD_TEST_GPIO1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOA7 (pin 9) */
    GPIO_PinSetPeripheralMode(BOARD_TEST_GPIO0_GPIO, BOARD_TEST_GPIO0_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOB0 (pin 24) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_B1_DACB_O);
    /* Enable peripheral functionality on pin GPIOB2 (pin 27) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* GPIO functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(BOARD_Bulk_OK_GPIO, BOARD_Bulk_OK_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C2_TXD0);
    /* Enable peripheral functionality on pin GPIOC3 (pin 7) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC3 (pin 7) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C3_RXD0);
    /* Enable peripheral functionality on pin GPIOC5 (pin 18) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC5 (pin 18) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C5_DACA_O);
    /* GPIO functionality on pin GPIOC8 (pin 33) */
    GPIO_PinSetPeripheralMode(BOARD_Bulk_High_Low_GPIO, BOARD_Bulk_High_Low_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC9 (pin 34) */
    GPIO_PinSetPeripheralMode(BOARD_B2B_On_GPIO, BOARD_B2B_On_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOC14 (pin 55) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin14, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC14 (pin 55) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C14_SDA0);
    /* Enable peripheral functionality on pin GPIOC15 (pin 56) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin15, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC15 (pin 56) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C15_SCL0);
    /* Enable peripheral functionality on pin GPIOD0 (pin 64) */
    GPIO_PinSetPeripheralMode(GPIOD, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOD1 (pin 62) */
    GPIO_PinSetPeripheralMode(GPIOD, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOD2 (pin 1) */
    GPIO_PinSetPeripheralMode(GPIOD, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOD3 (pin 63) */
    GPIO_PinSetPeripheralMode(GPIOD, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOD4 (pin 2) */
    GPIO_PinSetPeripheralMode(GPIOD, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E0_PWMA_0B);
    /* Enable peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E1_PWMA_0A);
    /* Enable peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E2_PWMA_1B);
    /* Enable peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E3_PWMA_1A);
    /* Enable peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E4_XB_OUT8);
    /* Enable peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E5_XB_OUT9);
    /* Enable peripheral functionality on pin GPIOF4 (pin 41) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF4 (pin 41) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F4_TXD1);
    /* Enable peripheral functionality on pin GPIOF5 (pin 42) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF5 (pin 42) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F5_RXD1);

    /* Initialize GPIO functionality on pin GPIOC8 (pin 33)  */
    GPIO_PinSetDirection(BOARD_Bulk_High_Low_GPIO, BOARD_Bulk_High_Low_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOA5 (pin 11)  */
    GPIO_PinWrite(BOARD_TEST_GPIO2_GPIO, BOARD_TEST_GPIO2_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_TEST_GPIO2_GPIO, BOARD_TEST_GPIO2_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOA6 (pin 10)  */
    GPIO_PinWrite(BOARD_TEST_GPIO1_GPIO, BOARD_TEST_GPIO1_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_TEST_GPIO1_GPIO, BOARD_TEST_GPIO1_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOA7 (pin 9)  */
    GPIO_PinWrite(BOARD_TEST_GPIO0_GPIO, BOARD_TEST_GPIO0_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_TEST_GPIO0_GPIO, BOARD_TEST_GPIO0_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC0 (pin 3)  */
    GPIO_PinWrite(BOARD_Bulk_OK_GPIO, BOARD_Bulk_OK_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_Bulk_OK_GPIO, BOARD_Bulk_OK_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC9 (pin 34)  */
    GPIO_PinWrite(BOARD_B2B_On_GPIO, BOARD_B2B_On_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_B2B_On_GPIO, BOARD_B2B_On_PIN_MASK, kGPIO_DigitalOutput);

    /* Internal Peripheral Select */
    /* Select PWMA Fault 0 Input.: Select PWMA Fault 0 Input, XB_OUT29. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault0InputIndex, kSIM_PWMAFault0Input_XB_OUT29);
    /* Select PWMA Fault 1 Input.: Select PWMA Fault 1 Input, XB_OUT30. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault1InputIndex, kSIM_PWMAFault1Input_XB_OUT30);

    /* PWM Select */
    /* xbar input 20.: xbar input 20, PWMA0_MUX_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN20Index, kSIM_XbarIn20PWMA0MuxTrig0);
    /* xbar input 21.: xbar input 21, PWMA0_MUX_TRIG1. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN21Index, kSIM_XbarIn21PWMA0MuxTrig1);

    /* CMPA_OUT output assigned to XBARA_IN12 input is connected
     * to XBARA_OUT29 output assigned to PWMA_PWMB_FAULT0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpaOut, kXBARA_OutputPwmaPwmbFault0);
    /* CMPB_OUT output assigned to XBARA_IN13 input is connected
     * to XBARA_OUT30 output assigned to PWMA_PWMB_FAULT1 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpbOut, kXBARA_OutputPwmaPwmbFault1);
    /* PWMA0_MUX_PWMB0_OUT_TRIG0 output assigned to XBARA_IN20 input is connected
     * to XBARA_OUT8 output assigned to XB_OUT8 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma0MuxPwmb0OutTrig0, kXBARA_OutputXbOut8);
    /* PWMA0_MUX_PWMB0_OUT_TRIG1 output assigned to XBARA_IN21 input is connected
     * to XBARA_OUT9 output assigned to XB_OUT9 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma0MuxPwmb0OutTrig1, kXBARA_OutputXbOut9);
    /* PIT0_SYNC_OUT output assigned to XBARA_IN44 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPit0SyncOut, kXBARA_OutputAdcaSync);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
