/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name GPIOA1 (number 14), I_LLC
  @{ */
#define BOARD_TP7_GPIO GPIOA          /*!<@brief GPIO device name: GPIOA */
#define BOARD_TP7_PIN 1U              /*!<@brief GPIOA pin index: 1 */
#define BOARD_TP7_PIN_MASK kGPIO_Pin1 /*!<@brief PORT pin mask */
                                      /* @} */

/*! @name GPIOA7 (number 9), TEST_GPIO0
  @{ */
#define BOARD_TEST_GPIO0_GPIO GPIOA          /*!<@brief GPIO device name: GPIOA */
#define BOARD_TEST_GPIO0_PIN 7U              /*!<@brief GPIOA pin index: 7 */
#define BOARD_TEST_GPIO0_PIN_MASK kGPIO_Pin7 /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name GPIOC0 (number 3), Bulk_OK
  @{ */
#define BOARD_Bulk_OK_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_Bulk_OK_PIN 0U              /*!<@brief GPIOC pin index: 0 */
#define BOARD_Bulk_OK_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name GPIOA6 (number 10), TEST_GPIO1
  @{ */
#define BOARD_TEST_GPIO1_GPIO GPIOA          /*!<@brief GPIO device name: GPIOA */
#define BOARD_TEST_GPIO1_PIN 6U              /*!<@brief GPIOA pin index: 6 */
#define BOARD_TEST_GPIO1_PIN_MASK kGPIO_Pin6 /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name GPIOA5 (number 11), TEST_GPIO2
  @{ */
#define BOARD_TEST_GPIO2_GPIO GPIOA          /*!<@brief GPIO device name: GPIOA */
#define BOARD_TEST_GPIO2_PIN 5U              /*!<@brief GPIOA pin index: 5 */
#define BOARD_TEST_GPIO2_PIN_MASK kGPIO_Pin5 /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name GPIOC8 (number 33), Bulk_High_Low
  @{ */
#define BOARD_Bulk_High_Low_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_Bulk_High_Low_PIN 8U              /*!<@brief GPIOC pin index: 8 */
#define BOARD_Bulk_High_Low_PIN_MASK kGPIO_Pin8 /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name GPIOC9 (number 34), B2B_On
  @{ */
#define BOARD_B2B_On_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_B2B_On_PIN 9U              /*!<@brief GPIOC pin index: 9 */
#define BOARD_B2B_On_PIN_MASK kGPIO_Pin9 /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name GPIOA0 (number 13), I_bat
  @{ */
#define BOARD_TP6_GPIO GPIOA          /*!<@brief GPIO device name: GPIOA */
#define BOARD_TP6_PIN 0U              /*!<@brief GPIOA pin index: 0 */
#define BOARD_TP6_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
